### ISSUE TITLE
DEP: prepare for pydantic 2.7.x

### ISSUE THREAD

**Issue by Segelzwerg** [Whist-Team/Whist-Core#398]
Fix

************* Module whist_core.session.table
whist_core/session/table.py:47:4: W0221: Number of parameters was 12 in 'BaseModel.model_dump' and is now 10 in overriding 'Table.model_dump' method (arguments-differ)
************* Module whist_core.game.hand
whist_core/game/hand.py:85:4: W0221: Number of parameters was 12 in 'BaseModel.model_dump' and is now 10 in overriding 'Hand.model_dump' method (arguments-differ)

**Comment by iTitus** [comment]
#442
