### ISSUE TITLE
Player system + Authentication

### ISSUE THREAD

**Issue by iTitus** [Whist-Team/Whist-Core#4]
We want to identify users and associate them with a self-chosen player name and id.

Question is:
- Login-System with password
- Session-based system that gives you a user id as a cookie (or something similar). The system will remember you as long you have that cookie. But what happens if it expires or you delete it? Any way to recover a session?

**Comment by Segelzwerg** [comment]
Let's have a discussion on the board https://github.com/Whist-Team/Whist-Core/discussions/7
